openapi: 3.0.3

info:
  title: Accounts Control Center
  description: Accounts microservice REST API
  version: 1.0

servers:
  - url: http://localhost:8081

paths:
  /v1/account/get:
    $ref: 'services/api/get-account.yaml#/endpoint'
  /v1/account/create:
    $ref: 'services/api/create-account.yaml#/endpoint'
  /v1/account/delete:
    $ref: 'services/api/delete-account.yaml#/endpoint'